name: Release dsd-ghidra

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: win32-x86-64
            target: x86_64-pc-windows-msvc
            file: dsd_ghidra.dll

          - os: ubuntu-latest
            name: linux-x86-64
            target: x86_64-unknown-linux-gnu
            file: libdsd_ghidra.so

          - os: macos-latest
            name: darwin-x86_64
            target: x86_64-apple-darwin
            file: libdsd_ghidra.dylib

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache Rust workspace
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Cargo build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/${{ matrix.file }}
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./dsd-ghidra/src/main/resources

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.5"

      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: "11.2.1"

      - name: Gradle build
        run: |
          gradle --project-dir dsd-ghidra --info --stacktrace

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: dsd-ghidra/dist/ghidra_*_dsd-ghidra.zip
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"
